name: neuropad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^11.5.0
  intl: ^0.20.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.6
  image_picker: ^1.2.1
  firebase_core: ^4.6.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  android_alarm_manager_plus: ^5.0.0
  shared_preferences: ^2.3.5
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Delius
      fonts:
        - asset: assets/fonts/Delius-Regular.ttf
          weight: 700


