// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtBAf9tMiXb1zZcMJIkHFD7O45jAmQWxI',
    appId: '1:143587575907:web:5172e9a67e70909a525056',
    messagingSenderId: '143587575907',
    projectId: 'notepad-app-4313d',
    authDomain: 'notepad-app-4313d.firebaseapp.com',
    storageBucket: 'notepad-app-4313d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnqko6j6s3sZPDGEN45BFsC7-byVeehaw',
    appId: '1:143587575907:android:cdf290dafa46d433525056',
    messagingSenderId: '143587575907',
    projectId: 'notepad-app-4313d',
    storageBucket: 'notepad-app-4313d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkqWv74muOGK0BBbKCh6OVSjUWQ3FhqmY',
    appId: '1:143587575907:ios:17eddae63daa28c8525056',
    messagingSenderId: '143587575907',
    projectId: 'notepad-app-4313d',
    storageBucket: 'notepad-app-4313d.firebasestorage.app',
    iosBundleId: 'com.example.neuropad',
  );

}